--- #YAML:1.0
name:               XML-Writer-Nest
version:            0.06
abstract:           dataElement() for when you need to embed elements, not data
author:
    - Terrence Brannon <metaperl@gmail.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Moose:       0
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.50
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
