---
abstract: 'work with XML writer using lexical scope'
author:
  - 'Terrence Brannon'
build_requires:
  Test::More: 0
  Test::XML: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200008, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Writer-Nest
requires:
  Moose: 0
  XML::Writer: 0
version: 1.111990
